name: Make OpenWRT raspi 4 88x2bu image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Requirements
        run: |
          sudo apt update
          sudo apt install tree build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget -y
      - name: Clone Repos
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git pull
          git checkout v24.10.2
      - name: Update & Install Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Clone 88x2bu-openwrt repo
        run: |
          cd openwrt
          git clone https://github.com/mirobiala/rtl88x2bu-cl package/kernel/rtl88x2bu-cl
          cd package/kernel/rtl88x2bu-cl
          git checkout v1.3.1
      - name: Dump Configs
        run: |
          cd openwrt
          curl https://raw.githubusercontent.com/ElytrA8-ops/openwrt-88x2bu/refs/heads/main/config -o .config
      - name: Its Baking Time 
        run: |
           cd openwrt
           echo using $(nproc) cores
           make -j$(nproc)
      - uses: actions/upload-artifact@v4
        with:
          name: RaspberryPi
          path: openwrt/bin/targets/bcm27xx/bcm2711/*.img.gz
