name: Test YML

on:
  #push:
    #branches: ['main']
    #branches: ['openwrt-*']
    #tags: ['v*']
  #pull_request:
    #branches: ['main']
    #branches: ['openwrt-*']
  workflow_dispatch:

jobs:
  first:
    name: First job

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: rtl88x2bu-cl
          fetch-depth: 0 # all history for tags and branches, needed to resolve tag->branch name
      - name: Get OpenWRT tag name
        shell: bash
        run: |
          echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"
          if [ ${{ github.ref_type }} == 'tag' ]; then
            echo "GITHUB_SHA = $GITHUB_SHA"
            git for-each-ref | grep ^$GITHUB_SHA | grep origin | grep -v HEAD
            OPENWRT_TAG=`git for-each-ref | grep ^$GITHUB_SHA | grep origin | grep -v HEAD | head -n1 | sed "s/.*\///"`
          else
            OPENWRT_TAG=$GITHUB_REF_NAME
          fi
          echo -e "OPENWRT_TAG=$(v`echo $OPENWRT_TAG | grep -o "[0-9].*"`)" >> $GITHUB_OUTPUT
        id: get_openwrt_tag
     - name: Print result
          OPENWRT_TAG=${{ steps.get_openwrt_tag.outputs.OPENWRT_TAG }}
          echo $OPENWRT_TAG
